src/Entity/EvaluationTask.php
<?php

namespace App\Entity;

use App\Repository\EvaluationTaskRepository;
use App\Entity\SegmentPair;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvaluationTaskRepository::class)
 */
class EvaluationTask
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $src_lang;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $trg_lang;

    /**
     * @ORM\Column(type="string", length=1024, nullable=true)
     */
    private $video;

    /**
     * One annotation task has many segments
     * @ORM\OneToMany(targetEntity="SegmentPair", mappedBy="task")
     */
    private $segments;

    /**
     * @ORM\Column(type="string", length=1024)
     */
    private $title;

    public function __construct()
    {
        $this->segments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSrcLang(): ?string
    {
        return $this->src_lang;
    }

    public function setSrcLang(string $src_lang): self
    {
        $this->src_lang = $src_lang;

        return $this;
    }

    public function getTrgLang(): ?string
    {
        return $this->trg_lang;
    }

    public function setTrgLang(string $trg_lang): self
    {
        $this->trg_lang = $trg_lang;

        return $this;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(?string $video): self
    {
        $this->video = $video;

        return $this;
    }

    public function getSegments()
    {
        return $this->segments;
    }

    public function addSegmentPair(SegmentPair $pair): self
    {
        $this->segments[] = $pair;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getFirst(): int
    {
        return $this->segments[0]->getId();
    }

    public function calculateCompleteness(EntityManager $entityManager, User $user): array
    {
        $segments = $this->segments;
        $noAnnotated = 0;
        $total = $segments->count();

        foreach ($segments as $segment) {
            if($segment->findAnnotationByUser($entityManager, $user)) {
                $noAnnotated++;
            }
        }

        return [$noAnnotated, $total];
    }
}

src/Controller/FrontPageController.php
<?php

namespace App\Controller;

use App\Entity\Task4User;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;

class FrontPageController extends AbstractController
{
    /**
     * @Route("/", name="front_page")
     */
    public function index(): Response
    {
        // if here reset the video offset
        $session = new Session();
        $session->start();
        $session->set("video-offset", "0");

        $user = $this->getUser();

        if (! $user) {
            return $this->redirectToRoute('app_login');
        }

        // check whether the user is still valid (probably completely unnecessary)
        if(! $this->isUserValid($user)) {
            return $this->redirectToRoute('app_logout');
        }

        // get the tasks for this user
        $entityManager = $this->getDoctrine()->getManager();
        $tasks = $entityManager->getRepository(Task4User::class)
            ->findBy(['user' => $user]);

        $info_tasks = [];
        foreach($tasks as $task) {
            $info_tasks[] = [$task, $task->getTask()->calculateCompleteness($entityManager, $user)];
        }

        return $this->render('front_page/index.html.twig', [
            'user' => $this->getUser(),
            'info_tasks' => $info_tasks,
        ]);
    }

    private function isUserValid(User $user): bool
    {
        $entityManager = $this->getDoctrine()->getManager();
        $userDatabase = $entityManager->getRepository(User::class)
                ->find($user->getId());
        if($userDatabase) {
            return true;
        } else {
            return false;
        }
    }
}

templates/front_page/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evaluation interface{% endblock %}

{% block body %}
<div class="row vspace2 justify-content-md-center">
    <div class="col-md-8">
        <div class="text-right">Hello: {{ user.email }} (<a href="{{ path("app_logout") }}">Not you?</a>) </div>

        <div class="vspace3 with-border">
            Here can be an short explanation of the task and what's on the screen
        </div>

        <h4 class="vspace3">List of tasks available for you</h4>
        <table class="table table-striped vspace2">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col" class="text-center">Progress</th>
                <th scope="col" class="text-center">Complete?</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for info_task in info_tasks %}
                <tr>
                    {% set task=info_task[0] %}
                    <th scope="row">{{ loop.index }}</th>
                    <td>{{ task.task.title }}</td>
                    <td class="text-center">{{ info_task[1][0] }}/{{ info_task[1][1] }}</td>
                    <td class="text-center">
                        {%  if task.complete %}
                            <i class="text-success fas fa-check left-margin-1em"></i>
                        {% else %}
                            <i class="text-danger fas fa-times left-margin-1em"></i>
                        {%  endif %}
                    </td>
                    <td>
                        <a href="{{ path('annotation', {'id': task.task.first}) }}">Annotate</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% if is_granted('ROLE_ADMIN') %}
    <div class="row justify-content-md-center vspace2">
        <div class="col-md-8">
            <h4>Admin tasks</h4>
            <ul>
                <li><a href="{{ path('admin-tasks') }}">Manage evaluation tasks</a></li>
            </ul>
        </div>
    </div>
{% endif %}
{% endblock %}